homeassistant:
  name: Klevans Home
  elevation: 17
  unit_system: metric
  time_zone: Europe/Stockholm

frontend:
config:
updater:
discovery:
history:
logbook:
cloud:
lovelace:
homekit:
  name: "Klevans Hassio"
system_health:

mqtt:
  broker: !secret mqtt_broker

# Example configuration.yaml entry
light:
  - platform: mqtt
    name: Lyktan
    unique_id: lyktan
    command_topic: "commands/relay/1"
    state_topic: "events/relay/1"
  - platform: mqtt
    name: Skomakarlamporna
    unique_id: skomakarlamporna
    command_topic: "commands/relay/2"
    state_topic: "events/relay/2"
  # - platform: mqtt
  #   name: switch 3
  #   command_topic: "commands/relay/3"
  #   state_topic: "events/relay/3"
  - platform: mqtt
    name: Jordgloben
    unique_id: jordgloben
    command_topic: "commands/relay/4"
    state_topic: "events/relay/4"

  - platform: mqtt
    name: Bakom TVn
    schema: json
    unique_id: tvbacklight
    command_topic: "commands/tvbacklight"
    rgb: true
    brightness: true
    effect: true
    effect_list:
      - colorloop

sensor:
  - platform: yr

  - platform: mqtt
    state_topic: "events/temperature"
    value_template: "{{ value_json.temperature }}"
    name: "Outside temperature"
    unit_of_measurement: '°C'

binary_sensor:
  - platform: mqtt
    state_topic: "events/movement"
    name: "Rörelsesensorn"

