homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 17
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  # Customization file
  # customize: !include customize.yaml

# device_tracker:
#   - platform: icloud
#     username: !secret icloud_user
#     password: !secret icloud_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

lovelace:

homekit:

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml

#influxdb:
#  host: worker0

mqtt:
  broker: worker0

# Example configuration.yaml entry
light:
  - platform: mqtt
    name: Lyktan
    unique_id: lyktan
    command_topic: "commands/relay/1"
    state_topic: "events/relay/1"
  - platform: mqtt
    name: Skomakarlamporna
    unique_id: skomakarlamporna
    command_topic: "commands/relay/2"
    state_topic: "events/relay/2"
  # - platform: mqtt
  #   name: switch 3
  #   command_topic: "commands/relay/3"
  #   state_topic: "events/relay/3"
  - platform: mqtt
    name: Jordgloben
    unique_id: jordgloben
    command_topic: "commands/relay/4"
    state_topic: "events/relay/4"

  #  - platform: mqtt
  # name: Inne hos detektiven
  # command_topic: "commands/lego/1"
  # state_topic: "events/lego/1"
  #- platform: mqtt
  #  name: Detektivens utebelysning
  #  command_topic: "commands/lego/2"
  #  state_topic: "events/lego/2"
  #- platform: mqtt
  #  name: Inne i restaurangen
  #  command_topic: "commands/lego/3"
  #  state_topic: "events/lego/3"
  #- platform: mqtt
  #  name: Restaurangens utebelysning
  #  command_topic: "commands/lego/4"
  #  state_topic: "events/lego/4"

  - platform: mqtt
    name: Bakom TVn
    schema: json
    unique_id: tvbacklight
    command_topic: "commands/tvbacklight"
    rgb_state_topic: "events/tvbacklight/rgb"
    brightness_state_topic: "events/tvbacklight/brightness"
    rgb: true
    brightness: true

sensor:
  - platform: yr

  - platform: mqtt
    state_topic: "events/temperature"
    value_template: "{{ value_json.temperature }}"
    name: "Outside temperature"
    unit_of_measurement: '°C'

binary_sensor:
  - platform: mqtt
    state_topic: "events/movement"
    name: "Rörelsesensorn"

