version: '3'
services:
  homeassistant:
    container_name: home-assistant
    # image: homeassistant/raspberrypi3-homeassistant:0.85.1
    image: homeassistant/home-assistant:0.85.1
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Stockholm
    restart: always
    ports:
      - 8123:8123
  mosqitto:
    container_name: mosqitto
    # image: pascaldevink/rpi-mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
