  - platform: mqtt
    name: Lyktan
    unique_id: lyktan
    command_topic: "commands/relay/1"
    state_topic: "events/relay/1"
  - platform: mqtt
    name: Skomakarlamporna
    unique_id: skomakarlamporna
    command_topic: "commands/relay/2"
    state_topic: "events/relay/2"
  - platform: mqtt
    name: Skåpet
    unique_id: skapet
    command_topic: "commands/relay/3"
    state_topic: "events/relay/3"
  - platform: mqtt
    name: Jordgloben
    unique_id: jordgloben
    command_topic: "commands/relay/4"
    state_topic: "events/relay/4"

  - platform: mqtt
    name: Bakom TVn
    schema: json
    unique_id: tvbacklight
    command_topic: "commands/tvbacklight"
    rgb: true
    brightness: true

  - platform: group
    name: Taklampan
    entities:
      - light.taklampa_1
      - light.taklampa_2
      - light.taklampa_3

  - platform: group
    name: Kloten
    entities:
      - light.hoger_klot
      - light.vanster_klot
